### model
model_name_or_path: /home/wmy2024/workspace/BEA-20/Model/Qwen2.5-32B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: mrbench_v3_devset_V02_train
template: qwen
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/BEA-20_T4/full/sft/Qwen2.5-32B-Instruct_V0101
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
save_steps: 25

### eval
eval_dataset: mrbench_v3_devset_V02_dev
# val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
